from .database import engine, Base
from .models import VocabularyLevel
import json

def init_database():
    """初始化数据库表"""
    Base.metadata.create_all(bind=engine)
    print("Database tables created successfully")

def seed_vocabulary_levels():
    """种子数据：导入CEFR词汇等级"""
    from .database import SessionLocal

    # 示例词汇数据（实际应该导入完整的CEFR词库）
    sample_words = [
        # A1级别 - 基础词汇 (常用词)
        {"word": "the", "level": "A1", "meaning": "这；那", "phonetic": "/ðə/", "example": "The book is on the table."},
        {"word": "be", "level": "A1", "meaning": "是；成为", "phonetic": "/biː/", "example": "I want to be a teacher."},
        {"word": "have", "level": "A1", "meaning": "有", "phonetic": "/hæv/", "example": "I have a cat."},
        {"word": "do", "level": "A1", "meaning": "做", "phonetic": "/duː/", "example": "What do you do?"},
        {"word": "say", "level": "A1", "meaning": "说", "phonetic": "/seɪ/", "example": "What did you say?"},
        {"word": "go", "level": "A1", "meaning": "去", "phonetic": "/ɡoʊ/", "example": "Let's go home."},
        {"word": "get", "level": "A1", "meaning": "得到", "phonetic": "/ɡet/", "example": "I got a gift."},
        {"word": "make", "level": "A1", "meaning": "制作", "phonetic": "/meɪk/", "example": "Make a wish."},
        {"word": "know", "level": "A1", "meaning": "知道", "phonetic": "/noʊ/", "example": "I know the answer."},
        {"word": "think", "level": "A1", "meaning": "想；认为", "phonetic": "/θɪŋk/", "example": "I think so."},
        {"word": "take", "level": "A1", "meaning": "拿；取", "phonetic": "/teɪk/", "example": "Take your time."},
        {"word": "see", "level": "A1", "meaning": "看见", "phonetic": "/siː/", "example": "I see what you mean."},
        {"word": "come", "level": "A1", "meaning": "来", "phonetic": "/kʌm/", "example": "Come here, please."},
        {"word": "want", "level": "A1", "meaning": "想要", "phonetic": "/wɑːnt/", "example": "I want some water."},
        {"word": "use", "level": "A1", "meaning": "使用", "phonetic": "/juːz/", "example": "Can I use your phone?"},
        {"word": "find", "level": "A1", "meaning": "找到", "phonetic": "/faɪnd/", "example": "I can't find my keys."},
        {"word": "give", "level": "A1", "meaning": "给", "phonetic": "/ɡɪv/", "example": "Give me your hand."},
        {"word": "tell", "level": "A1", "meaning": "告诉", "phonetic": "/tel/", "example": "Tell me the truth."},
        {"word": "work", "level": "A1", "meaning": "工作", "phonetic": "/wɜːrk/", "example": "I work in a hospital."},
        {"word": "call", "level": "A1", "meaning": "打电话；叫", "phonetic": "/kɔːl/", "example": "I'll call you tomorrow."},
        {"word": "try", "level": "A1", "meaning": "尝试", "phonetic": "/traɪ/", "example": "Try your best."},
        {"word": "need", "level": "A1", "meaning": "需要", "phonetic": "/niːd/", "example": "I need help."},
        {"word": "feel", "level": "A1", "meaning": "感觉", "phonetic": "/fiːl/", "example": "I feel happy."},
        {"word": "become", "level": "A1", "meaning": "变成", "phonetic": "/bɪˈkʌm/", "example": "She became a doctor."},
        {"word": "leave", "level": "A1", "meaning": "离开", "phonetic": "/liːv/", "example": "Don't leave me."},
        {"word": "put", "level": "A1", "meaning": "放置", "phonetic": "/pʊt/", "example": "Put it on the table."},
        {"word": "mean", "level": "A1", "meaning": "意思是", "phonetic": "/miːn/", "example": "What does this word mean?"},
        {"word": "keep", "level": "A1", "meaning": "保持；保留", "phonetic": "/kiːp/", "example": "Keep calm and carry on."},
        {"word": "let", "level": "A1", "meaning": "让", "phonetic": "/let/", "example": "Let me help you."},
        {"word": "begin", "level": "A1", "meaning": "开始", "phonetic": "/bɪˈɡɪn/", "example": "Let's begin the meeting."},
        {"word": "seem", "level": "A1", "meaning": "似乎", "phonetic": "/siːm/", "example": "It seems like a good idea."},
        {"word": "help", "level": "A1", "meaning": "帮助", "phonetic": "/help/", "example": "Can you help me?"},
        {"word": "show", "level": "A1", "meaning": "展示", "phonetic": "/ʃoʊ/", "example": "Show me your passport."},
        {"word": "hear", "level": "A1", "meaning": "听见", "phonetic": "/hɪr/", "example": "I hear music."},
        {"word": "play", "level": "A1", "meaning": "玩；演奏", "phonetic": "/pleɪ/", "example": "Let's play a game."},
        {"word": "run", "level": "A1", "meaning": "跑", "phonetic": "/rʌn/", "example": "Run as fast as you can."},
        {"word": "move", "level": "A1", "meaning": "移动", "phonetic": "/muːv/", "example": "Don't move."},
        {"word": "live", "level": "A1", "meaning": "生活；居住", "phonetic": "/lɪv/", "example": "I live in Beijing."},
        {"word": "believe", "level": "A1", "meaning": "相信", "phonetic": "/bɪˈliːv/", "example": "I believe you."},
        {"word": "bring", "level": "A1", "meaning": "带来", "phonetic": "/brɪŋ/", "example": "Bring your umbrella."},
        {"word": "happen", "level": "A1", "meaning": "发生", "phonetic": "/ˈhæpən/", "example": "What happened?"},
        {"word": "write", "level": "A1", "meaning": "写", "phonetic": "/raɪt/", "example": "Write your name here."},
        {"word": "provide", "level": "A1", "meaning": "提供", "phonetic": "/prəˈvaɪd/", "example": "We provide free WiFi."},
        {"word": "sit", "level": "A1", "meaning": "坐", "phonetic": "/sɪt/", "example": "Please sit down."},
        {"word": "stand", "level": "A1", "meaning": "站立", "phonetic": "/stænd/", "example": "Stand up, please."},
        {"word": "lose", "level": "A1", "meaning": "失去；输掉", "phonetic": "/luːz/", "example": "Don't lose hope."},
        {"word": "pay", "level": "A1", "meaning": "支付", "phonetic": "/peɪ/", "example": "I'll pay for dinner."},
        {"word": "meet", "level": "A1", "meaning": "遇见", "phonetic": "/miːt/", "example": "Nice to meet you."},
        {"word": "include", "level": "A1", "meaning": "包括", "phonetic": "/ɪnˈkluːd/", "example": "The price includes tax."},
        {"word": "continue", "level": "A1", "meaning": "继续", "phonetic": "/kənˈtɪnjuː/", "example": "Please continue."},
        {"word": "set", "level": "A1", "meaning": "设置", "phonetic": "/set/", "example": "Set the alarm."},
        {"word": "learn", "level": "A1", "meaning": "学习", "phonetic": "/lɜːrn/", "example": "I want to learn Chinese."},
        {"word": "change", "level": "A1", "meaning": "改变", "phonetic": "/tʃeɪndʒ/", "example": "Things will change."},
        {"word": "lead", "level": "A1", "meaning": "领导", "phonetic": "/liːd/", "example": "She leads the team."},
        {"word": "understand", "level": "A1", "meaning": "理解", "phonetic": "/ˌʌndərˈstænd/", "example": "I don't understand."},
        {"word": "watch", "level": "A1", "meaning": "观看", "phonetic": "/wɑːtʃ/", "example": "Let's watch a movie."},
        {"word": "follow", "level": "A1", "meaning": "跟随", "phonetic": "/ˈfɑːloʊ/", "example": "Follow me."},
        {"word": "stop", "level": "A1", "meaning": "停止", "phonetic": "/stɑːp/", "example": "Stop right there."},
        {"word": "create", "level": "A1", "meaning": "创造", "phonetic": "/kriˈeɪt/", "example": "Create something beautiful."},
        {"word": "speak", "level": "A1", "meaning": "说话", "phonetic": "/spiːk/", "example": "Speak louder, please."},
        {"word": "read", "level": "A1", "meaning": "阅读", "phonetic": "/riːd/", "example": "I like to read."},
        {"word": "allow", "level": "A1", "meaning": "允许", "phonetic": "/əˈlaʊ/", "example": "Smoking is not allowed."},
        {"word": "add", "level": "A1", "meaning": "添加", "phonetic": "/æd/", "example": "Add salt to taste."},
        {"word": "spend", "level": "A1", "meaning": "花费", "phonetic": "/spend/", "example": "I spent all my money."},
        {"word": "grow", "level": "A1", "meaning": "成长", "phonetic": "/ɡroʊ/", "example": "Plants grow fast."},
        {"word": "open", "level": "A1", "meaning": "打开", "phonetic": "/ˈoʊpən/", "example": "Open the door."},
        {"word": "walk", "level": "A1", "meaning": "走路", "phonetic": "/wɔːk/", "example": "Let's walk to school."},
        {"word": "offer", "level": "A1", "meaning": "提供；出价", "phonetic": "/ˈɔːfər/", "example": "He offered me a job."},
        {"word": "remember", "level": "A1", "meaning": "记得", "phonetic": "/rɪˈmembər/", "example": "I remember you."},
        {"word": "love", "level": "A1", "meaning": "爱", "phonetic": "/lʌv/", "example": "I love you."},
        {"word": "consider", "level": "A1", "meaning": "考虑", "phonetic": "/kənˈsɪdər/", "example": "Consider this option."},
        {"word": "appear", "level": "A1", "meaning": "出现", "phonetic": "/əˈpɪr/", "example": "She suddenly appeared."},
        {"word": "buy", "level": "A1", "meaning": "买", "phonetic": "/baɪ/", "example": "I want to buy a car."},
        {"word": "wait", "level": "A1", "meaning": "等待", "phonetic": "/weɪt/", "example": "Wait for me."},
        {"word": "serve", "level": "A1", "meaning": "服务", "phonetic": "/sɜːrv/", "example": "Serve the customers."},
        {"word": "die", "level": "A1", "meaning": "死亡", "phonetic": "/daɪ/", "example": "The plant will die."},
        {"word": "send", "level": "A1", "meaning": "发送", "phonetic": "/send/", "example": "Send me an email."},
        {"word": "expect", "level": "A1", "meaning": "期望", "phonetic": "/ɪkˈspekt/", "example": "I expect you to come."},
        {"word": "build", "level": "A1", "meaning": "建造", "phonetic": "/bɪld/", "example": "Build a house."},
        {"word": "stay", "level": "A1", "meaning": "停留", "phonetic": "/steɪ/", "example": "Stay here."},
        {"word": "fall", "level": "A1", "meaning": "落下", "phonetic": "/fɔːl/", "example": "Don't fall down."},
        {"word": "cut", "level": "A1", "meaning": "切", "phonetic": "/kʌt/", "example": "Cut the paper."},
        {"word": "reach", "level": "A1", "meaning": "到达", "phonetic": "/riːtʃ/", "example": "Reach for the stars."},
        {"word": "kill", "level": "A1", "meaning": "杀死", "phonetic": "/kɪl/", "example": "The cold killed the plant."},
        {"word": "remain", "level": "A1", "meaning": "保持", "phonetic": "/rɪˈmeɪn/", "example": "Please remain seated."},
        {"word": "suggest", "level": "A1", "meaning": "建议", "phonetic": "/səɡˈdʒest/", "example": "I suggest we wait."},
        {"word": "raise", "level": "A1", "meaning": "举起；提高", "phonetic": "/reɪz/", "example": "Raise your hand."},
        {"word": "pass", "level": "A1", "meaning": "通过", "phonetic": "/pæs/", "example": "Pass the salt."},
        {"word": "sell", "level": "A1", "meaning": "卖", "phonetic": "/sel/", "example": "Sell the car."},
        {"word": "require", "level": "A1", "meaning": "要求", "phonetic": "/rɪˈkwaɪər/", "example": "What do you require?"},
        {"word": "report", "level": "A1", "meaning": "报告", "phonetic": "/rɪˈpɔːrt/", "example": "Report to the office."},
        {"word": "decide", "level": "A1", "meaning": "决定", "phonetic": "/dɪˈsaɪd/", "example": "Decide what to do."},
        {"word": "pull", "level": "A1", "meaning": "拉", "phonetic": "/pʊl/", "example": "Pull the door."},

        # A2级别 - 初级词汇
        {"word": "quick", "level": "A2", "meaning": "快速的", "phonetic": "/kwɪk/", "example": "Be quick!"},
        {"word": "brown", "level": "A1", "meaning": "棕色", "phonetic": "/braʊn/", "example": "I like brown shoes."},
        {"word": "lazy", "level": "A2", "meaning": "懒惰的", "phonetic": "/ˈleɪzi/", "example": "Don't be lazy."},
        {"word": "over", "level": "A2", "meaning": "在...上方；越过", "phonetic": "/ˈoʊvər/", "example": "The bird flew over the house."},
        {"word": "always", "level": "A2", "meaning": "总是", "phonetic": "/ˈɔːlweɪz/", "example": "She always arrives early."},
        {"word": "never", "level": "A2", "meaning": "从不", "phonetic": "/ˈnevər/", "example": "I never give up."},
        {"word": "often", "level": "A2", "meaning": "经常", "phonetic": "/ˈɔːfn/", "example": "I often read books."},
        {"word": "already", "level": "A2", "meaning": "已经", "phonetic": "/ɔːlˈredi/", "example": "I've already finished."},
        {"word": "enough", "level": "A2", "meaning": "足够的", "phonetic": "/ɪˈnʌf/", "example": "That's enough."},
        {"word": "almost", "level": "A2", "meaning": "几乎", "phonetic": "/ˈɔːlmoʊst/", "example": "It's almost time."},
        {"word": "able", "level": "A2", "meaning": "能够的", "phonetic": "/ˈeɪbl/", "example": "I am able to help."},
        {"word": "away", "level": "A2", "meaning": "离开", "phonetic": "/əˈweɪ/", "example": "Go away!"},

        {"word": "busy", "level": "A2", "meaning": "忙碌的", "phonetic": "/ˈbɪzi/", "example": "I'm very busy."},
        {"word": "care", "level": "A2", "meaning": "关心", "phonetic": "/ker/", "example": "I don't care."},
        {"word": "carry", "level": "A2", "meaning": "携带", "phonetic": "/ˈkæri/", "example": "Carry this bag."},
        {"word": "clear", "level": "A2", "meaning": "清楚的", "phonetic": "/klɪr/", "example": "The water is clear."},
        {"word": "close", "level": "A2", "meaning": "关闭", "phonetic": "/kloʊz/", "example": "Close the door."},
        {"word": "complete", "level": "A2", "meaning": "完成", "phonetic": "/kəmˈpliːt/", "example": "Complete the task."},
        {"word": "cost", "level": "A2", "meaning": "花费", "phonetic": "/kɔːst/", "example": "How much does it cost?"},
        {"word": "course", "level": "A2", "meaning": "课程", "phonetic": "/kɔːrs/", "example": "Take a course."},
        {"word": "cover", "level": "A2", "meaning": "覆盖", "phonetic": "/ˈkʌvər/", "example": "Cover the food."},
        {"word": "describe", "level": "A2", "meaning": "描述", "phonetic": "/dɪˈskraɪb/", "example": "Describe the picture."},
        {"word": "during", "level": "A2", "meaning": "在...期间", "phonetic": "/ˈdjʊrɪŋ/", "example": "During the meeting."},
        {"word": "early", "level": "A2", "meaning": "早的", "phonetic": "/ˈɜːrli/", "example": "Get up early."},
        {"word": "easy", "level": "A2", "meaning": "容易的", "phonetic": "/ˈiːzi/", "example": "It's very easy."},
        {"word": "effort", "level": "A2", "meaning": "努力", "phonetic": "/ˈefərt/", "example": "Make an effort."},
        {"word": "either", "level": "A2", "meaning": "也（否定）", "phonetic": "/ˈaɪðər/", "example": "I don't like it either."},
        {"word": "enjoy", "level": "A2", "meaning": "享受", "phonetic": "/ɪnˈdʒɔɪ/", "example": "Enjoy your meal."},
        {"word": "especially", "level": "A2", "meaning": "尤其", "phonetic": "/ɪˈspeʃəli/", "example": "I love chocolate, especially dark."},
        {"word": "every", "level": "A2", "meaning": "每个", "phonetic": "/ˈevri/", "example": "Every day is special."},
        {"word": "explain", "level": "A2", "meaning": "解释", "phonetic": "/ɪkˈspleɪn/", "example": "Explain the rules."},
        {"word": "famous", "level": "A2", "meaning": "著名的", "phonetic": "/ˈfeɪməs/", "example": "She is famous."},
        {"word": "favorite", "level": "A2", "meaning": "最喜欢的", "phonetic": "/ˈfeɪvərɪt/", "example": "My favorite color."},
        {"word": "finally", "level": "A2", "meaning": "最后", "phonetic": "/ˈfaɪnəli/", "example": "Finally, we're done."},
        {"word": "foreign", "level": "A2", "meaning": "外国的", "phonetic": "/ˈfɔːrən/", "example": "A foreign language."},
        {"word": "former", "level": "A2", "meaning": "以前的", "phonetic": "/ˈfɔːrmər/", "example": "My former boss."},
        {"word": "forward", "level": "A2", "meaning": "向前", "phonetic": "/ˈfɔːrwərd/", "example": "Move forward."},
        {"word": "further", "level": "A2", "meaning": "更远的", "phonetic": "/ˈfɜːrðər/", "example": "For further information."},
        {"word": "general", "level": "A2", "meaning": "一般的", "phonetic": "/ˈdʒenrəl/", "example": "In general, yes."},
        {"word": "however", "level": "A2", "meaning": "然而", "phonetic": "/haʊˈevər/", "example": "However, it's true."},
        {"word": "increase", "level": "A2", "meaning": "增加", "phonetic": "/ɪnˈkriːs/", "example": "Increase the speed."},
        {"word": "instead", "level": "A2", "meaning": "代替", "phonetic": "/ɪnˈsted/", "example": "Go instead of me."},
        {"word": "issue", "level": "A2", "meaning": "问题", "phonetic": "/ˈɪʃuː/", "example": "There's an issue."},
        {"word": "itself", "level": "A2", "meaning": "它自己", "phonetic": "/ɪtˈself/", "example": "The door closed itself."},
        {"word": "likely", "level": "A2", "meaning": "可能的", "phonetic": "/ˈlaɪkli/", "example": "It's likely to rain."},
        {"word": "local", "level": "A2", "meaning": "当地的", "phonetic": "/ˈloʊkl/", "example": "Local news."},
        {"word": "main", "level": "A2", "meaning": "主要的", "phonetic": "/meɪn/", "example": "The main reason."},
        {"word": "maybe", "level": "A2", "meaning": "也许", "phonetic": "/ˈmeɪbi/", "example": "Maybe later."},
        {"word": "measure", "level": "A2", "meaning": "测量", "phonetic": "/ˈmeʒər/", "example": "Measure the length."},
        {"word": "mention", "level": "A2", "meaning": "提到", "phonetic": "/ˈmenʃn/", "example": "Don't mention it."},
        {"word": "modern", "level": "A2", "meaning": "现代的", "phonetic": "/ˈmɑːdərn/", "example": "Modern technology."},
        {"word": "nearby", "level": "A2", "meaning": "附近的", "phonetic": "/ˈnɪrbaɪ/", "example": "A nearby restaurant."},
        {"word": "nearly", "level": "A2", "meaning": "几乎", "phonetic": "/ˈnɪrli/", "example": "Nearly finished."},
        {"word": "obvious", "level": "A2", "meaning": "明显的", "phonetic": "/ˈɑːbviəs/", "example": "It's obvious."},
        {"word": "particular", "level": "A2", "meaning": "特别的", "phonetic": "/pərˈtɪkjələr/", "example": "In particular."},
        {"word": "perhaps", "level": "A2", "meaning": "也许", "phonetic": "/pərˈhæps/", "example": "Perhaps you're right."},
        {"word": "please", "level": "A2", "meaning": "请", "phonetic": "/pliːz/", "example": "Please help me."},
        {"word": "present", "level": "A2", "meaning": "现在的；礼物", "phonetic": "/ˈpreznt/", "example": "At the present time."},
        {"word": "probably", "level": "A2", "meaning": "可能", "phonetic": "/ˈprɑːbəbli/", "example": "Probably true."},
        {"word": "recent", "level": "A2", "meaning": "最近的", "phonetic": "/ˈriːsnt/", "example": "A recent event."},
        {"word": "reduce", "level": "A2", "meaning": "减少", "phonetic": "/rɪˈduːs/", "example": "Reduce the cost."},
        {"word": "remove", "level": "A2", "meaning": "移除", "phonetic": "/rɪˈmuːv/", "example": "Remove the lid."},
        {"word": "result", "level": "A2", "meaning": "结果", "phonetic": "/rɪˈzʌlt/", "example": "As a result."},
        {"word": "return", "level": "A2", "meaning": "返回", "phonetic": "/rɪˈtɜːrn/", "example": "Return home."},
        {"word": "serious", "level": "A2", "meaning": "严肃的", "phonetic": "/ˈsɪriəs/", "example": "Be serious."},
        {"word": "several", "level": "A2", "meaning": "几个", "phonetic": "/ˈsevrəl/", "example": "Several times."},
        {"word": "similar", "level": "A2", "meaning": "相似的", "phonetic": "/ˈsɪmɪlər/", "example": "Very similar."},
        {"word": "simple", "level": "A2", "meaning": "简单的", "phonetic": "/ˈsɪmpl/", "example": "A simple task."},
        {"word": "since", "level": "A2", "meaning": "自从", "phonetic": "/sɪns/", "example": "Since then."},
        {"word": "social", "level": "A2", "meaning": "社会的", "phonetic": "/ˈsoʊʃl/", "example": "Social media."},
        {"word": "special", "level": "A2", "meaning": "特别的", "phonetic": "/ˈspeʃl/", "example": "A special day."},
        {"word": "staff", "level": "A2", "meaning": "员工", "phonetic": "/stæf/", "example": "The hotel staff."},
        {"word": "store", "level": "A2", "meaning": "商店", "phonetic": "/stɔːr/", "example": "A grocery store."},
        {"word": "support", "level": "A2", "meaning": "支持", "phonetic": "/səˈpɔːrt/", "example": "Support your team."},
        {"word": "therefore", "level": "A2", "meaning": "因此", "phonetic": "/ˈðerfɔːr/", "example": "Therefore, I agree."},
        {"word": "though", "level": "A2", "meaning": "虽然", "phonetic": "/ðoʊ/", "example": "Even though."},
        {"word": "throughout", "level": "A2", "meaning": "遍及", "phonetic": "/θruːˈaʊt/", "example": "Throughout the year."},
        {"word": "various", "level": "A2", "meaning": "各种各样的", "phonetic": "/ˈveriəs/", "example": "Various colors."},
        {"word": "wonder", "level": "A2", "meaning": "想知道", "phonetic": "/ˈwʌndər/", "example": "I wonder why."},
        {"word": "worry", "level": "A2", "meaning": "担心", "phonetic": "/ˈwʌri/", "example": "Don't worry."},
        {"word": "worth", "level": "A2", "meaning": "值得的", "phonetic": "/wɜːrθ/", "example": "It's worth it."},

        # B1级别 - 中级词汇
        {"word": "fox", "level": "B1", "meaning": "狐狸", "phonetic": "/fɑːks/", "example": "The fox is clever."},
        {"word": "jump", "level": "B1", "meaning": "跳跃", "phonetic": "/dʒʌmp/", "example": "Can you jump high?"},
        {"word": "accomplish", "level": "B1", "meaning": "完成；实现", "phonetic": "/əˈkɑːmplɪʃ/", "example": "We accomplished our goal."},
        {"word": "challenge", "level": "B1", "meaning": "挑战", "phonetic": "/ˈtʃælɪndʒ/", "example": "This is a big challenge."},
        {"word": "develop", "level": "B1", "meaning": "发展；开发", "phonetic": "/dɪˈveləp/", "example": "We need to develop new skills."},
        {"word": "environment", "level": "B1", "meaning": "环境", "phonetic": "/ɪnˈvaɪrənmənt/", "example": "Protect the environment."},
        {"word": "experience", "level": "B1", "meaning": "经验；经历", "phonetic": "/ɪkˈspɪriəns/", "example": "She has lots of experience."},
        {"word": "improve", "level": "B1", "meaning": "改善；提高", "phonetic": "/ɪmˈpruːv/", "example": "I want to improve my English."},
        {"word": "knowledge", "level": "B1", "meaning": "知识", "phonetic": "/ˈnɑːlɪdʒ/", "example": "Knowledge is power."},
        {"word": "opportunity", "level": "B1", "meaning": "机会", "phonetic": "/ˌɑːpərˈtuːnəti/", "example": "This is a great opportunity."},
        {"word": "access", "level": "B1", "meaning": "访问；进入", "phonetic": "/ˈækses/", "example": "Gain access to data."},
        {"word": "achieve", "level": "B1", "meaning": "达到", "phonetic": "/əˈtʃiːv/", "example": "Achieve your goals."},
        {"word": "affect", "level": "B1", "meaning": "影响", "phonetic": "/əˈfekt/", "example": "Affect the outcome."},
        {"word": "approach", "level": "B1", "meaning": "方法", "phonetic": "/əˈproʊtʃ/", "example": "A new approach."},
        {"word": "appropriate", "level": "B1", "meaning": "适当的", "phonetic": "/əˈproʊpriət/", "example": "An appropriate response."},
        {"word": "assume", "level": "B1", "meaning": "假设", "phonetic": "/əˈsuːm/", "example": "Assume responsibility."},
        {"word": "attitude", "level": "B1", "meaning": "态度", "phonetic": "/ˈætɪtuːd/", "example": "A positive attitude."},
        {"word": "available", "level": "B1", "meaning": "可用的", "phonetic": "/əˈveɪləbl/", "example": "Available now."},
        {"word": "benefit", "level": "B1", "meaning": "好处", "phonetic": "/ˈbenɪfɪt/", "example": "Health benefits."},
        {"word": "beyond", "level": "B1", "meaning": "超越", "phonetic": "/bɪˈjɑːnd/", "example": "Beyond expectations."},
        {"word": "capable", "level": "B1", "meaning": "有能力的", "phonetic": "/ˈkeɪpəbl/", "example": "Capable of change."},
        {"word": "claim", "level": "B1", "meaning": "声称", "phonetic": "/kleɪm/", "example": "Claim victory."},
        {"word": "combine", "level": "B1", "meaning": "结合", "phonetic": "/kəmˈbaɪn/", "example": "Combine the ingredients."},
        {"word": "compare", "level": "B1", "meaning": "比较", "phonetic": "/kəmˈper/", "example": "Compare and contrast."},
        {"word": "concern", "level": "B1", "meaning": "关心；担忧", "phonetic": "/kənˈsɜːrn/", "example": "Cause for concern."},
        {"word": "conclude", "level": "B1", "meaning": "结论", "phonetic": "/kənˈkluːd/", "example": "Conclude the speech."},
        {"word": "confirm", "level": "B1", "meaning": "确认", "phonetic": "/kənˈfɜːrm/", "example": "Confirm the reservation."},
        {"word": "consequence", "level": "B1", "meaning": "后果", "phonetic": "/ˈkɑːnsəkwens/", "example": "Face the consequences."},
        {"word": "contribute", "level": "B1", "meaning": "贡献", "phonetic": "/kənˈtrɪbjuːt/", "example": "Contribute to society."},
        {"word": "declare", "level": "B1", "meaning": "宣布", "phonetic": "/dɪˈkler/", "example": "Declare war."},
        {"word": "define", "level": "B1", "meaning": "定义", "phonetic": "/dɪˈfaɪn/", "example": "Define the term."},
        {"word": "demand", "level": "B1", "meaning": "需求；要求", "phonetic": "/dɪˈmænd/", "example": "High demand."},
        {"word": "deny", "level": "B1", "meaning": "否认", "phonetic": "/dɪˈnaɪ/", "example": "Deny the accusation."},
        {"word": "desire", "level": "B1", "meaning": "欲望", "phonetic": "/dɪˈzaɪər/", "example": "A burning desire."},
        {"word": "determine", "level": "B1", "meaning": "决定；查明", "phonetic": "/dɪˈtɜːrmɪn/", "example": "Determine the cause."},
        {"word": "distinguish", "level": "B1", "meaning": "区分", "phonetic": "/dɪˈstɪŋɡwɪʃ/", "example": "Distinguish between them."},
        {"word": "domestic", "level": "B1", "meaning": "国内的", "phonetic": "/dəˈmestɪk/", "example": "Domestic policy."},
        {"word": "eliminate", "level": "B1", "meaning": "消除", "phonetic": "/ɪˈlɪmɪneɪt/", "example": "Eliminate the problem."},
        {"word": "encourage", "level": "B1", "meaning": "鼓励", "phonetic": "/ɪnˈkʌrɪdʒ/", "example": "Encourage creativity."},
        {"word": "ensure", "level": "B1", "meaning": "确保", "phonetic": "/ɪnˈʃʊr/", "example": "Ensure safety."},
        {"word": "establish", "level": "B1", "meaning": "建立", "phonetic": "/ɪˈstæblɪʃ/", "example": "Establish a company."},
        {"word": "examine", "level": "B1", "meaning": "检查", "phonetic": "/ɪɡˈzæmɪn/", "example": "Examine the evidence."},
        {"word": "exist", "level": "B1", "meaning": "存在", "phonetic": "/ɪɡˈzɪst/", "example": "Does it exist?"},
        {"word": "expand", "level": "B1", "meaning": "扩展", "phonetic": "/ɪkˈspænd/", "example": "Expand the business."},
        {"word": "fee", "level": "B1", "meaning": "费用", "phonetic": "/fiː/", "example": "A small fee."},
        {"word": "focus", "level": "B1", "meaning": "集中", "phonetic": "/ˈfoʊkəs/", "example": "Focus on the task."},
        {"word": "function", "level": "B1", "meaning": "功能", "phonetic": "/ˈfʌŋkʃn/", "example": "The function of the heart."},
        {"word": "fund", "level": "B1", "meaning": "资金", "phonetic": "/fʌnd/", "example": "Raise funds."},
        {"word": "gain", "level": "B1", "meaning": "获得", "phonetic": "/ɡeɪn/", "example": "Gain experience."},
        {"word": "generate", "level": "B1", "meaning": "产生", "phonetic": "/ˈdʒenəreɪt/", "example": "Generate electricity."},
        {"word": "grant", "level": "B1", "meaning": "授予；拨款", "phonetic": "/ɡrænt/", "example": "Grant permission."},
        {"word": "hence", "level": "B1", "meaning": "因此", "phonetic": "/hens/", "example": "Hence the problem."},
        {"word": "illustrate", "level": "B1", "meaning": "说明", "phonetic": "/ˈɪləstreɪt/", "example": "Illustrate the point."},
        {"word": "imply", "level": "B1", "meaning": "暗示", "phonetic": "/ɪmˈplaɪ/", "example": "What do you imply?"},
        {"word": "initial", "level": "B1", "meaning": "最初的", "phonetic": "/ɪˈnɪʃl/", "example": "The initial plan."},
        {"word": "injury", "level": "B1", "meaning": "伤害", "phonetic": "/ˈɪndʒəri/", "example": "Serious injury."},
        {"word": "investigate", "level": "B1", "meaning": "调查", "phonetic": "/ɪnˈvestɪɡeɪt/", "example": "Investigate the crime."},
        {"word": "lack", "level": "B1", "meaning": "缺乏", "phonetic": "/læk/", "example": "Lack of sleep."},
        {"word": "maintain", "level": "B1", "meaning": "维持", "phonetic": "/meɪnˈteɪn/", "example": "Maintain order."},
        {"word": "manner", "level": "B1", "meaning": "方式", "phonetic": "/ˈmænər/", "example": "In a polite manner."},
        {"word": "minor", "level": "B1", "meaning": "次要的", "phonetic": "/ˈmaɪnər/", "example": "A minor problem."},
        {"word": "neglect", "level": "B1", "meaning": "忽视", "phonetic": "/nɪˈɡlekt/", "example": "Neglect your duty."},
        {"word": "obtain", "level": "B1", "meaning": "获得", "phonetic": "/əbˈteɪn/", "example": "Obtain permission."},
        {"word": "participate", "level": "B1", "meaning": "参加", "phonetic": "/pɑːrˈtɪsɪpeɪt/", "example": "Participate in events."},
        {"word": "permit", "level": "B1", "meaning": "允许", "phonetic": "/pərˈmɪt/", "example": "Permit entry."},
        {"word": "potential", "level": "B1", "meaning": "潜在的", "phonetic": "/pəˈtenʃl/", "example": "Great potential."},
        {"word": "propose", "level": "B1", "meaning": "提议", "phonetic": "/prəˈpoʊz/", "example": "Propose a solution."},
        {"word": "range", "level": "B1", "meaning": "范围", "phonetic": "/reɪndʒ/", "example": "A wide range."},
        {"word": "recognize", "level": "B1", "meaning": "认出", "phonetic": "/ˈrekəɡnaɪz/", "example": "Recognize the voice."},
        {"word": "reveal", "level": "B1", "meaning": "揭示", "phonetic": "/rɪˈviːl/", "example": "Reveal the truth."},
        {"word": "seek", "level": "B1", "meaning": "寻找", "phonetic": "/siːk/", "example": "Seek advice."},
        {"word": "select", "level": "B1", "meaning": "选择", "phonetic": "/sɪˈlekt/", "example": "Select an option."},
        {"word": "significant", "level": "B1", "meaning": "重要的", "phonetic": "/sɪɡˈnɪfɪkənt/", "example": "A significant change."},
        {"word": "structure", "level": "B1", "meaning": "结构", "phonetic": "/ˈstrʌktʃər/", "example": "Building structure."},
        {"word": "submit", "level": "B1", "meaning": "提交", "phonetic": "/səbˈmɪt/", "example": "Submit the form."},
        {"word": "suffer", "level": "B1", "meaning": "遭受", "phonetic": "/ˈsʌfər/", "example": "Suffer from pain."},
        {"word": "survive", "level": "B1", "meaning": "幸存", "phonetic": "/sərˈvaɪv/", "example": "Survive the storm."},
        {"word": "threat", "level": "B1", "meaning": "威胁", "phonetic": "/θret/", "example": "A serious threat."},
        {"word": "tradition", "level": "B1", "meaning": "传统", "phonetic": "/trəˈdɪʃn/", "example": "Family tradition."},
        {"word": "unique", "level": "B1", "meaning": "独特的", "phonetic": "/juˈniːk/", "example": "A unique opportunity."},
        {"word": "unite", "level": "B1", "meaning": "联合", "phonetic": "/juˈnaɪt/", "example": "Unite the people."},
        {"word": "vast", "level": "B1", "meaning": "广阔的", "phonetic": "/væst/", "example": "A vast ocean."},
        {"word": "victim", "level": "B1", "meaning": "受害者", "phonetic": "/ˈvɪktɪm/", "example": "A crime victim."},
        {"word": "vision", "level": "B1", "meaning": "愿景", "phonetic": "/ˈvɪʒn/", "example": "A clear vision."},
        {"word": "wealth", "level": "B1", "meaning": "财富", "phonetic": "/welθ/", "example": "Wealth and power."},
        {"word": "witness", "level": "B1", "meaning": "目击", "phonetic": "/ˈwɪtnəs/", "example": "Witness the event."},

        # B2级别 - 中高级词汇
        {"word": "sophisticated", "level": "B2", "meaning": "复杂的；精密的", "phonetic": "/səˈfɪstɪkeɪtɪd/", "example": "This is a sophisticated system."},
        {"word": "comprehensive", "level": "B2", "meaning": "全面的；综合的", "phonetic": "/ˌkɑːmprɪˈhensɪv/", "example": "We need a comprehensive plan."},
        {"word": "phenomenon", "level": "B2", "meaning": "现象", "phonetic": "/fəˈnɑːmɪnən/", "example": "This is an interesting phenomenon."},
        {"word": "perspective", "level": "B2", "meaning": "观点；视角", "phonetic": "/pərˈspektɪv/", "example": "From my perspective..."},
        {"word": "acknowledge", "level": "B2", "meaning": "承认", "phonetic": "/əkˈnɑːlɪdʒ/", "example": "Acknowledge the mistake."},
        {"word": "advocate", "level": "B2", "meaning": "倡导", "phonetic": "/ˈædvəkeɪt/", "example": "Advocate for change."},
        {"word": "allocate", "level": "B2", "meaning": "分配", "phonetic": "/ˈæloʊkeɪt/", "example": "Allocate resources."},
        {"word": "anticipate", "level": "B2", "meaning": "预料", "phonetic": "/ænˈtɪsɪpeɪt/", "example": "Anticipate the result."},
        {"word": "apparent", "level": "B2", "meaning": "明显的", "phonetic": "/əˈpærənt/", "example": "An apparent error."},
        {"word": "assess", "level": "B2", "meaning": "评估", "phonetic": "/əˈses/", "example": "Assess the damage."},
        {"word": "attribute", "level": "B2", "meaning": "归因于", "phonetic": "/əˈtrɪbjuːt/", "example": "Attribute success to hard work."},
        {"word": "compensate", "level": "B2", "meaning": "补偿", "phonetic": "/ˈkɑːmpenseɪt/", "example": "Compensate for the loss."},
        {"word": "comply", "level": "B2", "meaning": "遵守", "phonetic": "/kəmˈplaɪ/", "example": "Comply with the rules."},
        {"word": "conceal", "level": "B2", "meaning": "隐藏", "phonetic": "/kənˈsiːl/", "example": "Conceal the truth."},
        {"word": "convey", "level": "B2", "meaning": "传达", "phonetic": "/kənˈveɪ/", "example": "Convey a message."},
        {"word": "decline", "level": "B2", "meaning": "下降；拒绝", "phonetic": "/dɪˈklaɪn/", "example": "Decline an offer."},
        {"word": "deliberate", "level": "B2", "meaning": "故意的", "phonetic": "/dɪˈlɪbərət/", "example": "A deliberate act."},
        {"word": "deliberately", "level": "B2", "meaning": "故意地", "phonetic": "/dɪˈlɪbərətli/", "example": "Done deliberately."},
        {"word": "diminish", "level": "B2", "meaning": "减少", "phonetic": "/dɪˈmɪnɪʃ/", "example": "Diminish the risk."},
        {"word": "discriminate", "level": "B2", "meaning": "歧视", "phonetic": "/dɪˈskrɪmɪneɪt/", "example": "Discriminate against."},
        {"word": "dispose", "level": "B2", "meaning": "处理", "phonetic": "/dɪˈspoʊz/", "example": "Dispose of waste."},
        {"word": "distinct", "level": "B2", "meaning": "不同的", "phonetic": "/dɪˈstɪŋkt/", "example": "A distinct advantage."},
        {"word": "elaborate", "level": "B2", "meaning": "详细的", "phonetic": "/ɪˈlæbərət/", "example": "An elaborate plan."},
        {"word": "emphasis", "level": "B2", "meaning": "强调", "phonetic": "/ˈemfəsɪs/", "example": "Place emphasis on."},
        {"word": "exceed", "level": "B2", "meaning": "超过", "phonetic": "/ɪkˈsiːd/", "example": "Exceed expectations."},
        {"word": "exert", "level": "B2", "meaning": "施加", "phonetic": "/ɪɡˈzɜːrt/", "example": "Exert pressure."},
        {"word": "facilitate", "level": "B2", "meaning": "促进", "phonetic": "/fəˈsɪlɪteɪt/", "example": "Facilitate communication."},
        {"word": "feasible", "level": "B2", "meaning": "可行的", "phonetic": "/ˈfiːzəbl/", "example": "A feasible plan."},
        {"word": "fluctuate", "level": "B2", "meaning": "波动", "phonetic": "/ˈflʌktʃueɪt/", "example": "Prices fluctuate."},
        {"word": "formulate", "level": "B2", "meaning": "制定", "phonetic": "/ˈfɔːrmjuleɪt/", "example": "Formulate a plan."},
        {"word": "genuine", "level": "B2", "meaning": "真正的", "phonetic": "/ˈdʒenjuɪn/", "example": "A genuine offer."},
        {"word": "hinder", "level": "B2", "meaning": "阻碍", "phonetic": "/ˈhɪndər/", "example": "Hinder progress."},
        {"word": "illuminate", "level": "B2", "meaning": "照亮", "phonetic": "/ɪˈluːmɪneɪt/", "example": "Illuminate the room."},
        {"word": "impose", "level": "B2", "meaning": "强加", "phonetic": "/ɪmˈpoʊz/", "example": "Impose restrictions."},
        {"word": "induce", "level": "B2", "meaning": "引起", "phonetic": "/ɪnˈduːs/", "example": "Induce sleep."},
        {"word": "infer", "level": "B2", "meaning": "推断", "phonetic": "/ɪnˈfɜːr/", "example": "Infer from data."},
        {"word": "inhibit", "level": "B2", "meaning": "抑制", "phonetic": "/ɪnˈhɪbɪt/", "example": "Inhibit growth."},
        {"word": "intrinsic", "level": "B2", "meaning": "内在的", "phonetic": "/ɪnˈtrɪnzɪk/", "example": "Intrinsic value."},
        {"word": "justify", "level": "B2", "meaning": "证明...正当", "phonetic": "/ˈdʒʌstɪfaɪ/", "example": "Justify the decision."},
        {"word": "manipulate", "level": "B2", "meaning": "操纵", "phonetic": "/məˈnɪpjuleɪt/", "example": "Manipulate data."},
        {"word": "merge", "level": "B2", "meaning": "合并", "phonetic": "/mɜːrdʒ/", "example": "Merge the files."},
        {"word": "modify", "level": "B2", "meaning": "修改", "phonetic": "/ˈmɑːdɪfaɪ/", "example": "Modify the plan."},
        {"word": "notion", "level": "B2", "meaning": "概念", "phonetic": "/ˈnoʊʃn/", "example": "The notion of freedom."},
        {"word": "obscure", "level": "B2", "meaning": "模糊的", "phonetic": "/əbˈskjʊr/", "example": "An obscure reference."},
        {"word": "omit", "level": "B2", "meaning": "省略", "phonetic": "/oʊˈmɪt/", "example": "Omit the details."},
        {"word": "persist", "level": "B2", "meaning": "坚持", "phonetic": "/pərˈsɪst/", "example": "Persist in trying."},
        {"word": "precede", "level": "B2", "meaning": "先于", "phonetic": "/prɪˈsiːd/", "example": "Precede the event."},
        {"word": "prohibit", "level": "B2", "meaning": "禁止", "phonetic": "/proʊˈhɪbɪt/", "example": "Prohibit smoking."},
        {"word": "promote", "level": "B2", "meaning": "促进", "phonetic": "/prəˈmoʊt/", "example": "Promote health."},
        {"word": "recur", "level": "B2", "meaning": "复发", "phonetic": "/rɪˈkɜːr/", "example": "Problems recur."},
        {"word": "reform", "level": "B2", "meaning": "改革", "phonetic": "/rɪˈfɔːrm/", "example": "Reform the system."},
        {"word": "reinforce", "level": "B2", "meaning": "加强", "phonetic": "/ˌriːɪnˈfɔːrs/", "example": "Reinforce the message."},
        {"word": "restrain", "level": "B2", "meaning": "抑制", "phonetic": "/rɪˈstreɪn/", "example": "Restrain your anger."},
        {"word": "retain", "level": "B2", "meaning": "保留", "phonetic": "/rɪˈteɪn/", "example": "Retain information."},
        {"word": "sustain", "level": "B2", "meaning": "维持", "phonetic": "/səˈsteɪn/", "example": "Sustain growth."},
        {"word": "transform", "level": "B2", "meaning": "转变", "phonetic": "/trænsˈfɔːrm/", "example": "Transform the business."},
        {"word": "undermine", "level": "B2", "meaning": "破坏", "phonetic": "/ˌʌndərˈmaɪn/", "example": "Undermine confidence."},
        {"word": "undertake", "level": "B2", "meaning": "承担", "phonetic": "/ˌʌndərˈteɪk/", "example": "Undertake a task."},

        # C1级别 - 高级词汇
        {"word": "ubiquitous", "level": "C1", "meaning": "无处不在的", "phonetic": "/juːˈbɪkwɪtəs/", "example": "Smartphones are ubiquitous."},
        {"word": "paradigm", "level": "C1", "meaning": "范例；典范", "phonetic": "/ˈpærədaɪm/", "example": "This is a new paradigm."},
        {"word": "ephemeral", "level": "C1", "meaning": "短暂的", "phonetic": "/ɪˈfemərəl/", "example": "Fame can be ephemeral."},
        {"word": "pragmatic", "level": "C1", "meaning": "务实的", "phonetic": "/præɡˈmætɪk/", "example": "We need a pragmatic approach."},
        {"word": "resilient", "level": "C1", "meaning": "有弹性的；适应力强的", "phonetic": "/rɪˈzɪliənt/", "example": "Children are resilient."},
        {"word": "ambiguous", "level": "C1", "meaning": "模棱两可的", "phonetic": "/æmˈbɪɡjuəs/", "example": "An ambiguous statement."},
        {"word": "analogous", "level": "C1", "meaning": "类似的", "phonetic": "/əˈnæləɡəs/", "example": "An analogous situation."},
        {"word": "arbitrary", "level": "C1", "meaning": "任意的", "phonetic": "/ˈɑːrbɪtreri/", "example": "An arbitrary decision."},
        {"word": "coherent", "level": "C1", "meaning": "连贯的", "phonetic": "/koʊˈhɪrənt/", "example": "A coherent argument."},
        {"word": "commence", "level": "C1", "meaning": "开始", "phonetic": "/kəˈmens/", "example": "Commence the meeting."},
        {"word": "consensus", "level": "C1", "meaning": "共识", "phonetic": "/kənˈsensəs/", "example": "Reach a consensus."},
        {"word": "contradict", "level": "C1", "meaning": "反驳", "phonetic": "/ˈkɑːntrədɪkt/", "example": "Contradict the theory."},
        {"word": "converge", "level": "C1", "meaning": "汇聚", "phonetic": "/kənˈvɜːrdʒ/", "example": "Roads converge."},
        {"word": "corrode", "level": "C1", "meaning": "腐蚀", "phonetic": "/kəˈroʊd/", "example": "Metal corrodes."},
        {"word": "culminate", "level": "C1", "meaning": "达到顶点", "phonetic": "/ˈkʌlmɪneɪt/", "example": "Culminate in success."},
        {"word": "deplete", "level": "C1", "meaning": "耗尽", "phonetic": "/dɪˈpliːt/", "example": "Deplete resources."},
        {"word": "discrepancy", "level": "C1", "meaning": "差异", "phonetic": "/dɪˈskrepənsi/", "example": "A discrepancy in data."},
        {"word": "elicit", "level": "C1", "meaning": "引出", "phonetic": "/ɪˈlɪsɪt/", "example": "Elicit a response."},
        {"word": "erode", "level": "C1", "meaning": "侵蚀", "phonetic": "/ɪˈroʊd/", "example": "Erode the soil."},
        {"word": "exacerbate", "level": "C1", "meaning": "加剧", "phonetic": "/ɪɡˈzæsərbeɪt/", "example": "Exacerbate the problem."},
        {"word": "fluctuation", "level": "C1", "meaning": "波动", "phonetic": "/ˌflʌktʃuˈeɪʃn/", "example": "Price fluctuations."},
        {"word": "grandiose", "level": "C1", "meaning": "宏伟的", "phonetic": "/ˈɡrændioʊs/", "example": "A grandiose plan."},
        {"word": "hypothesis", "level": "C1", "meaning": "假设", "phonetic": "/haɪˈpɑːθəsɪs/", "example": "Test a hypothesis."},
        {"word": "implausible", "level": "C1", "meaning": "难以置信的", "phonetic": "/ɪmˈplɔːzəbl/", "example": "An implausible story."},
        {"word": "indigenous", "level": "C1", "meaning": "土著的", "phonetic": "/ɪnˈdɪdʒənəs/", "example": "Indigenous people."},
        {"word": "lucid", "level": "C1", "meaning": "清晰的", "phonetic": "/ˈluːsɪd/", "example": "A lucid explanation."},
        {"word": "mitigate", "level": "C1", "meaning": "减轻", "phonetic": "/ˈmɪtɪɡeɪt/", "example": "Mitigate the damage."},
        {"word": "narrative", "level": "C1", "meaning": "叙述", "phonetic": "/ˈnærətɪv/", "example": "A compelling narrative."},
        {"word": "notwithstanding", "level": "C1", "meaning": "尽管", "phonetic": "/ˌnɑːtwɪθˈstændɪŋ/", "example": "Notwithstanding the difficulties."},
        {"word": "plausible", "level": "C1", "meaning": "貌似合理的", "phonetic": "/ˈplɔːzəbl/", "example": "A plausible excuse."},
        {"word": "precarious", "level": "C1", "meaning": "不稳定的", "phonetic": "/prɪˈkeriəs/", "example": "A precarious situation."},
        {"word": "predominant", "level": "C1", "meaning": "占主导地位的", "phonetic": "/prɪˈdɑːmɪnənt/", "example": "The predominant factor."},
        {"word": "profound", "level": "C1", "meaning": "深刻的", "phonetic": "/prəˈfaʊnd/", "example": "A profound impact."},
        {"word": "rectify", "level": "C1", "meaning": "纠正", "phonetic": "/ˈrektɪfaɪ/", "example": "Rectify the error."},
        {"word": "redundant", "level": "C1", "meaning": "多余的", "phonetic": "/rɪˈdʌndənt/", "example": "Redundant information."},
        {"word": "relinquish", "level": "C1", "meaning": "放弃", "phonetic": "/rɪˈlɪŋkwɪʃ/", "example": "Relinquish control."},
        {"word": "subsequent", "level": "C1", "meaning": "随后的", "phonetic": "/ˈsʌbsɪkwənt/", "example": "Subsequent events."},
        {"word": "subtle", "level": "C1", "meaning": "微妙的", "phonetic": "/ˈsʌtl/", "example": "A subtle difference."},
        {"word": "succinct", "level": "C1", "meaning": "简洁的", "phonetic": "/səkˈsɪŋkt/", "example": "A succinct summary."},

        # C2级别 - 精通级词汇
        {"word": "quintessential", "level": "C2", "meaning": "典型的；精髓的", "phonetic": "/ˌkwɪntɪˈsenʃl/", "example": "He is the quintessential gentleman."},
        {"word": "serendipity", "level": "C2", "meaning": "意外发现美好事物的运气", "phonetic": "/ˌserənˈdɪpəti/", "example": "Finding this place was pure serendipity."},
        {"word": "eloquent", "level": "C2", "meaning": "雄辩的；有说服力的", "phonetic": "/ˈeləkwənt/", "example": "She gave an eloquent speech."},
        {"word": "meticulous", "level": "C2", "meaning": "一丝不苟的", "phonetic": "/məˈtɪkjələs/", "example": "He is meticulous in his work."},
        {"word": "candid", "level": "C2", "meaning": "坦率的；公正的", "phonetic": "/ˈkændɪd/", "example": "To be candid with you..."},
        {"word": "aberration", "level": "C2", "meaning": "异常", "phonetic": "/ˌæbəˈreɪʃn/", "example": "A statistical aberration."},
        {"word": "acquiesce", "level": "C2", "meaning": "默许", "phonetic": "/ˌækwiˈes/", "example": "Acquiesce to demands."},
        {"word": "antithesis", "level": "C2", "meaning": "对立", "phonetic": "/ænˈtɪθəsɪs/", "example": "The antithesis of good."},
        {"word": "cogent", "level": "C2", "meaning": "有说服力的", "phonetic": "/ˈkoʊdʒənt/", "example": "A cogent argument."},
        {"word": "deference", "level": "C2", "meaning": "尊重", "phonetic": "/ˈdefərəns/", "example": "Show deference."},
        {"word": "didactic", "level": "C2", "meaning": "说教的", "phonetic": "/daɪˈdæktɪk/", "example": "A didactic story."},
        {"word": "egregious", "level": "C2", "meaning": "极坏的", "phonetic": "/ɪˈɡriːdʒəs/", "example": "An egregious error."},
        {"word": "exemplify", "level": "C2", "meaning": "例证", "phonetic": "/ɪɡˈzemplɪfaɪ/", "example": "Exemplify the point."},
        {"word": "fastidious", "level": "C2", "meaning": "挑剔的", "phonetic": "/fæˈstɪdiəs/", "example": "A fastidious critic."},
        {"word": "fortuitous", "level": "C2", "meaning": "偶然的", "phonetic": "/fɔːrˈtuːɪtəs/", "example": "A fortuitous meeting."},
        {"word": "grandiloquent", "level": "C2", "meaning": "夸张的", "phonetic": "/ɡrænˈdɪləkwənt/", "example": "Grandiloquent speech."},
        {"word": "heterogeneous", "level": "C2", "meaning": "异质的", "phonetic": "/ˌhetərəˈdʒiːniəs/", "example": "A heterogeneous group."},
        {"word": "incongruous", "level": "C2", "meaning": "不协调的", "phonetic": "/ɪnˈkɑːŋɡruəs/", "example": "An incongruous mix."},
        {"word": "insidious", "level": "C2", "meaning": "阴险的", "phonetic": "/ɪnˈsɪdiəs/", "example": "An insidious threat."},
        {"word": "magnanimous", "level": "C2", "meaning": "宽宏大量的", "phonetic": "/mæɡˈnænɪməs/", "example": "A magnanimous gesture."},
        {"word": "obfuscate", "level": "C2", "meaning": "混淆", "phonetic": "/ˈɑːbfəskeɪt/", "example": "Obfuscate the truth."},
        {"word": "perfidious", "level": "C2", "meaning": "背信弃义的", "phonetic": "/pərˈfɪdiəs/", "example": "A perfidious ally."},
        {"word": "perspicacious", "level": "C2", "meaning": "有洞察力的", "phonetic": "/ˌpɜːrspɪˈkeɪʃəs/", "example": "A perspicacious observer."},
        {"word": "plethora", "level": "C2", "meaning": "过多", "phonetic": "/ˈpleθərə/", "example": "A plethora of options."},
        {"word": "predilection", "level": "C2", "meaning": "偏好", "phonetic": "/ˌpredɪˈlekʃn/", "example": "A predilection for art."},
        {"word": "recalcitrant", "level": "C2", "meaning": "不服从的", "phonetic": "/rɪˈkælsɪtrənt/", "example": "A recalcitrant student."},
        {"word": "recondite", "level": "C2", "meaning": "深奥的", "phonetic": "/ˈrekəndaɪt/", "example": "A recondite subject."},
        {"word": "surreptitious", "level": "C2", "meaning": "秘密的", "phonetic": "/ˌsɜːrəpˈtɪʃəs/", "example": "A surreptitious glance."},
        {"word": "unprecedented", "level": "C2", "meaning": "前所未有的", "phonetic": "/ʌnˈpresɪdentɪd/", "example": "An unprecedented event."},
        {"word": "vacillate", "level": "C2", "meaning": "犹豫", "phonetic": "/ˈvæsɪleɪt/", "example": "Vacillate between options."},
        {"word": "vicissitude", "level": "C2", "meaning": "变迁", "phonetic": "/vɪˈsɪsɪtjuːd/", "example": "The vicissitudes of life."},
        {"word": "zeitgeist", "level": "C2", "meaning": "时代精神", "phonetic": "/ˈzaɪtɡaɪst/", "example": "Capture the zeitgeist."},
    ]

    db = SessionLocal()
    try:
        for word_data in sample_words:
            # 检查是否已存在
            existing = db.query(VocabularyLevel).filter(
                VocabularyLevel.word == word_data["word"]
            ).first()

            if not existing:
                vocab = VocabularyLevel(**word_data)
                db.add(vocab)

        db.commit()
        print(f"Successfully seeded {len(sample_words)} vocabulary words")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    init_database()
    seed_vocabulary_levels()
